const headerTemplate = (fileName, projectName) => `//
//  ${fileName}
//  ${projectName}
//
//  Generated by Zepcode on ${
    new Date().toLocaleDateString()
}.
//  Copyright © ${new Date().getFullYear()} __MyCompanyName__. All rights reserved.
//`;

export default headerTemplate;
