on: push
name: Run exec
jobs:
  build:
    name: Exec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g zem
    - run: npm run exec
