on: release
name: Test and Publish
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Test
    - run: npm test
    - name: Publish
      uses: artemnovichkov/action-zem@v0.3
      env:
        ZEM_ACCESS_TOKEN: ${{ secrets.ZEM_ACCESS_TOKEN }}
      with:
        args: publish
