on: 
  release:
    types: [published]
name: Build, Test, and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        npm i
        npm test
    - name: Publish
      uses: artemnovichkov/action-zem@master
      env:
        ZEM_ACCESS_TOKEN: ${{ secrets.ZEM_ACCESS_TOKEN }}
      with:
        args: publish
